pacman::p_load(RSQLite,
               DBI,
               magrittr,
               data.table,
               shiny,
               DT,
               lubridate,
               shinyjs)
initialDate=date(today())